create schema if not exists "MATCHESMALONE";

CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_001" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_002" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_003" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_004" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_005" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_006" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "MATCHESMALONE"."ARTIST"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_002" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_002",
    "NAME" VARCHAR(255),
    "ROLE" VARCHAR(255)
);
ALTER TABLE "MATCHESMALONE"."ARTIST" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_7" PRIMARY KEY("ID");

CREATE MEMORY TABLE "MATCHESMALONE"."ARTISTS_ISSUES"(
    "ARTIST_ID" BIGINT NOT NULL,
    "ISSUE_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "MATCHESMALONE"."BOOK_BR"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_004" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_004",
    "DATA" TIMESTAMP,
    "EDITORA" VARCHAR(255),
    "NOME" VARCHAR(255),
    "URL_COVER" VARCHAR(255)
);
ALTER TABLE "MATCHESMALONE"."BOOK_BR" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_2" PRIMARY KEY("ID");

CREATE MEMORY TABLE "MATCHESMALONE"."BOOKBR_ISSUES"(
    "BOOKBR_ID" BIGINT NOT NULL,
    "ISSUE_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "MATCHESMALONE"."BOOK_CHRONO"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_006" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_006",
    "DATE_PUBLISH" TIMESTAMP,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "ORDER_NUMBER" BIGINT,
    "URL_COVER" VARCHAR(255)
);
ALTER TABLE "MATCHESMALONE"."BOOK_CHRONO" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_D" PRIMARY KEY("ID");

CREATE MEMORY TABLE "MATCHESMALONE"."BOOKCHRONO_ISSUES"(
    "BOOKCHRONO_ID" BIGINT NOT NULL,
    "ISSUE_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "MATCHESMALONE"."COMICS_CHARACTER_BOOKCHRONO"(
    "BOOKCHRONO_ID" BIGINT NOT NULL,
    "COMICS_CHARACTER_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "MATCHESMALONE"."COMICS_CHARACTER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_001" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_001",
    "ALIASES" VARCHAR(255),
    "NAME" VARCHAR(255)
);
ALTER TABLE "MATCHESMALONE"."COMICS_CHARACTER" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_A" PRIMARY KEY("ID");

CREATE MEMORY TABLE "MATCHESMALONE"."ISSUE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_005" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_005",
    "NUMBER" BIGINT,
    "URL_COVER" VARCHAR(255),
    "VOLUME_ID" BIGINT
);
ALTER TABLE "MATCHESMALONE"."ISSUE" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_4" PRIMARY KEY("ID");

CREATE MEMORY TABLE "MATCHESMALONE"."VOLUME"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MATCHESMALONE"."SYSTEM_SEQUENCE_003" NOT NULL NULL_TO_DEFAULT SEQUENCE "MATCHESMALONE"."SYSTEM_SEQUENCE_003",
    "NAME" VARCHAR(255)
);
ALTER TABLE "MATCHESMALONE"."VOLUME" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_9" PRIMARY KEY("ID");

ALTER TABLE "MATCHESMALONE"."BOOKBR_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_10" FOREIGN KEY("ISSUE_ID") REFERENCES "MATCHESMALONE"."ISSUE"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."ISSUE" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_11" FOREIGN KEY("VOLUME_ID") REFERENCES "MATCHESMALONE"."VOLUME"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."ARTISTS_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_12" FOREIGN KEY("ARTIST_ID") REFERENCES "MATCHESMALONE"."ARTIST"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."BOOKCHRONO_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_13" FOREIGN KEY("ISSUE_ID") REFERENCES "MATCHESMALONE"."ISSUE"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."BOOKBR_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_14" FOREIGN KEY("BOOKBR_ID") REFERENCES "MATCHESMALONE"."BOOK_BR"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."BOOKCHRONO_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_15" FOREIGN KEY("BOOKCHRONO_ID") REFERENCES "MATCHESMALONE"."BOOK_CHRONO"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."ARTISTS_ISSUES" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_16" FOREIGN KEY("ISSUE_ID") REFERENCES "MATCHESMALONE"."ISSUE"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."COMICS_CHARACTER_BOOKCHRONO" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_17" FOREIGN KEY("COMICS_CHARACTER_ID") REFERENCES "MATCHESMALONE"."BOOK_CHRONO"("ID") NOCHECK;
ALTER TABLE "MATCHESMALONE"."COMICS_CHARACTER_BOOKCHRONO" ADD CONSTRAINT "MATCHESMALONE"."CONSTRAINT_18" FOREIGN KEY("BOOKCHRONO_ID") REFERENCES "MATCHESMALONE"."COMICS_CHARACTER"("ID") NOCHECK;

SET SCHEMA matchesmalone;